---
title: "Figures"
author: "Angela Crabtree"
date: "3/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r libraries}
library(RColorBrewer)
library(gplots)
library(dplyr)
library(svglite)
```

```{r import_custom_functions}
# import custom functions
source("dsrna-survey-functions.R")
```


```{r set_wd}
## set working directory
script_dir=dirname(rstudioapi::getSourceEditorContext()$path)
data_dir=paste0(unlist(strsplit(script_dir, "/scripts"))[1], "/data/")
setwd(data_dir)
## set image output directory
img_dir=paste0(unlist(strsplit(script_dir, "/scripts"))[1], "/img/")
```


## Results: Part 1

#### **Prevalence of killer yeasts**

```{r data_pt1}
# import data
killer_data_file = paste0(data_dir, "killer_assays.csv")
killer.df <- read.csv(killer_data_file, header = TRUE, na.strings = c('*'))
# remove rows where yeast did not grow
killer.df <- killer.df[which(killer.df$Y1088!="no yeast"),]
```

```{r fig1b}
# remove selected lawn column(s)
lawns_to_remove = c("ATCC2001")
killer.df = dplyr::select(killer.df, -contains(lawns_to_remove))

## make heatmap of canonical strains 
canonical_heatmap(killer.df, remove_lawns=lawns_to_remove)
```

```{r, eval=FALSE}
## save above plot as file
img_file = paste0(img_dir, "Fig1B_canonical_heatmap.svg") # filename
svglite(filename=img_file, 
    width=9, 
    height=5)
canonical_heatmap(killer.df) # Creating a plot (ignore error about margins)
#plot(x,y)
#dev.off()
```

```{r fig1d}
collapsed_heatmap(killer.df) 
```

```{r, eval=FALSE}
## save above plot as file
img_file = paste0(img_dir, "Fig1D_collapsed_heatmap.svg") # filename
svglite(filename=img_file, 
    width=9, 
    height=5)
collapsed_heatmap(killer.df) # Creating a plot (ignore error about margins)
```

```{r tbl1}

```

## Results: Part 2

#### **Identification of unknown toxins**

```{r data_pt2}

```

```{r tbl2}

```

```{r fig3ab}

```

```{r, eval=FALSE}
## save above plot as SVG file
img_file = paste0(img_dir, "Fig3ab_bubble_plots.svg") # filename
p = ggplot(mtcars, aes(x = wt, y = mpg)) + # Creating a plot
  geom_point()
ggsave(
  img_file,
  plot = p,
  width = 4, height = 4)
```

## Results: Part 2

#### **Genome-encoded toxins**

```{r data_pt3}

```

```{r tbl3}

```

```{r tbl4}

```

## Supplement

```{r data_supplement}

```

```{r figS1}

```

```{r figS4}

```

```{r figS5}

```

```{r figS6}

```

## R Session Info

```{r}
sessionInfo()
```

