#!/usr/bin/env Rscript

main <- function() {
  ###################### LIBRARIES ###################### 
  ## install bioconductor installer, if needed
  if (!requireNamespace("BiocManager")) install.packages("BiocManager")
  ## install and load required R packages
  if(!require(Biostrings)) BiocManager::install("Biostrings", dependencies = TRUE)
  library(Biostrings)
  if(!require(ggplot2)) install.packages("ggplot2", dependencies = TRUE)
  library(ggplot2)
  
  ###################### ARGPARSE ###################### 
  
  ## parse arguments
  args <- commandArgs(trailingOnly = TRUE)
  ## original blast input file generated by chrtox_blastn.sh
  chr_categories <- args[1]  
  data_dir <- gsub("(\\w+)/\\w+\\.csv", "\\1", chr_categories)[1]
  setwd(data_dir)
  ## revised blast input file generated by chrtox_blastn.sh
  chr_revised <- args[2]  
  # option for output filename 
  if (is.na(args[3])==FALSE){
    output_file <- args[3]
  } else {
    output_file <- paste0(data_dir, '/chr_compare.csv')
  }
  
  ###################### MAIN ###################### 

  ## import blast output file 
  table1 <- read.csv(chr_categories, header=T)
  # import extended revised file
  table2 <- read.csv(chr_revised, header = TRUE)
  # merge files
  mergedTbl = merge(table1,table2,by.x="contig",by.y="Contig",all=TRUE)
  for(i in 1:nrow(mergedTbl)){
    if (mergedTbl$aaseq[i] != mergedTbl$Prot[i]){ #This matches the new ORF aa with the original aa
      mergedTbl$ORFMatch[i] <- "Mismatch"
    }else {
      mergedTbl$ORFMatch[i] <- "Match"
    }
  }
  ## write full data file
  write.csv(mergedTbl, file=output_file, row.names = FALSE)
  ## write file containing only mismatched info
  mergedTbl_mismatched = mergedTbl[which(mergedTbl$ORFMatch=="Mismatch"),]
  write.csv(mergedTbl_mismatched, file=paste0(data_dir,"/chr_mismatched.csv"), 
            row.names = FALSE)
  
  # prepare data for plotting matches & mismatches
  mergedTbl$num_match = 1
  mergedTbl.collapsed = aggregate(num_match ~ gene+ORFMatch, data=mergedTbl, FUN=sum)
  
  ## plot hits 
  myPalette <- c("#984EA3", "#FFFB00")
  p = ggplot(data=mergedTbl.collapsed, aes(x=gene, y=num_match, fill=ORFMatch)) +
    geom_bar(stat="identity", position="stack", color="grey")  +
    theme_classic(base_size = 28) +
    labs(y="Strain Count", x="") +
    theme(axis.text.x = element_text(angle=315, hjust=0.2, vjust=0.5),
          plot.title = element_text(hjust = 0.5),
          panel.grid.major.y = element_line(
            size = 0.5, linetype = 'solid', colour = "grey"),
          plot.margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm"),
          legend.position = "right", legend.title=element_text(size=22),
          legend.text=element_text(size=22),
          legend.background = element_rect(
            fill="white", size=0.5, linetype="solid", colour ="black")) +
    scale_fill_manual("ORF Match?", values = myPalette) #+
    #ylim(0, length(unique(mergedTbl$filename)))
  # save plot to SVG file
  img_file = paste0(data_dir, "/05_chr_compare.svg") 
  ggsave(
    img_file,
    plot = p,
    width = 5, height = 4)
}
main()